version: '3.6'

services:

  #Backend API
  smart-brain-api:
    container_name: back-end
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
      # POSTGRES_USER: sally
      # POSTGRES_PASSWORD: secret
      # POSTGRES_DB: smart-brain-docker
      # POSTGRES_HOST: postgres
    links:
      - postgres
      - redis
    ports:
      - "3000:5000"
    #volumes:
    #  - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    # image: postgres   #contain container_name
    build: ./postgres
    ports:
      - "5400:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6300:6379"